# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sovisu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analizatordata',
            name='an_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='analizatordata',
            name='so_m_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='analizatordata',
            name='so_n_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='analizatordata',
            name='so_ug_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wth_date',
            field=models.DateTimeField(),
        ),
    ]
